//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Data.EntityClient;
using System.ComponentModel;
using System.Xml.Serialization;
using System.Runtime.Serialization;

[assembly: EdmSchemaAttribute()]
#region Metadatos de relaciones en EDM

[assembly: EdmRelationshipAttribute("dbuniversidadModel1", "FK__estudiant__codig__0BC6C43E", "carrera", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(SitioWebUniversidad.carrera), "estudiante", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(SitioWebUniversidad.estudiante), true)]
[assembly: EdmRelationshipAttribute("dbuniversidadModel1", "FK__detalleEv__codig__15502E78", "estudiante", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(SitioWebUniversidad.estudiante), "detalleEvaluacion", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(SitioWebUniversidad.detalleEvaluacion), true)]
[assembly: EdmRelationshipAttribute("dbuniversidadModel1", "FK__detalleEv__numer__164452B1", "evaluacion", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(SitioWebUniversidad.evaluacion), "detalleEvaluacion", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(SitioWebUniversidad.detalleEvaluacion), true)]
[assembly: EdmRelationshipAttribute("dbuniversidadModel1", "FK__evaluacio__sigla__108B795B", "materia", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(SitioWebUniversidad.materia), "evaluacion", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(SitioWebUniversidad.evaluacion), true)]

#endregion

namespace SitioWebUniversidad
{
    #region Contextos
    
    /// <summary>
    /// No hay documentación de metadatos disponible.
    /// </summary>
    public partial class dbuniversidadEntities1 : ObjectContext
    {
        #region Constructores
    
        /// <summary>
        /// Inicializa un nuevo objeto dbuniversidadEntities1 usando la cadena de conexión encontrada en la sección 'dbuniversidadEntities1' del archivo de configuración de la aplicación.
        /// </summary>
        public dbuniversidadEntities1() : base("name=dbuniversidadEntities1", "dbuniversidadEntities1")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Inicializar un nuevo objeto dbuniversidadEntities1.
        /// </summary>
        public dbuniversidadEntities1(string connectionString) : base(connectionString, "dbuniversidadEntities1")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Inicializar un nuevo objeto dbuniversidadEntities1.
        /// </summary>
        public dbuniversidadEntities1(EntityConnection connection) : base(connection, "dbuniversidadEntities1")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Métodos parciales
    
        partial void OnContextCreated();
    
        #endregion
    
        #region Propiedades de ObjectSet
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        public ObjectSet<carrera> carrera
        {
            get
            {
                if ((_carrera == null))
                {
                    _carrera = base.CreateObjectSet<carrera>("carrera");
                }
                return _carrera;
            }
        }
        private ObjectSet<carrera> _carrera;
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        public ObjectSet<detalleEvaluacion> detalleEvaluacion
        {
            get
            {
                if ((_detalleEvaluacion == null))
                {
                    _detalleEvaluacion = base.CreateObjectSet<detalleEvaluacion>("detalleEvaluacion");
                }
                return _detalleEvaluacion;
            }
        }
        private ObjectSet<detalleEvaluacion> _detalleEvaluacion;
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        public ObjectSet<estudiante> estudiante
        {
            get
            {
                if ((_estudiante == null))
                {
                    _estudiante = base.CreateObjectSet<estudiante>("estudiante");
                }
                return _estudiante;
            }
        }
        private ObjectSet<estudiante> _estudiante;
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        public ObjectSet<evaluacion> evaluacion
        {
            get
            {
                if ((_evaluacion == null))
                {
                    _evaluacion = base.CreateObjectSet<evaluacion>("evaluacion");
                }
                return _evaluacion;
            }
        }
        private ObjectSet<evaluacion> _evaluacion;
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        public ObjectSet<materia> materia
        {
            get
            {
                if ((_materia == null))
                {
                    _materia = base.CreateObjectSet<materia>("materia");
                }
                return _materia;
            }
        }
        private ObjectSet<materia> _materia;

        #endregion
        #region Métodos AddTo
    
        /// <summary>
        /// Método desusado para agregar un nuevo objeto al EntitySet carrera. Considere la posibilidad de usar el método .Add de la propiedad ObjectSet&lt;T&gt; asociada.
        /// </summary>
        public void AddTocarrera(carrera carrera)
        {
            base.AddObject("carrera", carrera);
        }
    
        /// <summary>
        /// Método desusado para agregar un nuevo objeto al EntitySet detalleEvaluacion. Considere la posibilidad de usar el método .Add de la propiedad ObjectSet&lt;T&gt; asociada.
        /// </summary>
        public void AddTodetalleEvaluacion(detalleEvaluacion detalleEvaluacion)
        {
            base.AddObject("detalleEvaluacion", detalleEvaluacion);
        }
    
        /// <summary>
        /// Método desusado para agregar un nuevo objeto al EntitySet estudiante. Considere la posibilidad de usar el método .Add de la propiedad ObjectSet&lt;T&gt; asociada.
        /// </summary>
        public void AddToestudiante(estudiante estudiante)
        {
            base.AddObject("estudiante", estudiante);
        }
    
        /// <summary>
        /// Método desusado para agregar un nuevo objeto al EntitySet evaluacion. Considere la posibilidad de usar el método .Add de la propiedad ObjectSet&lt;T&gt; asociada.
        /// </summary>
        public void AddToevaluacion(evaluacion evaluacion)
        {
            base.AddObject("evaluacion", evaluacion);
        }
    
        /// <summary>
        /// Método desusado para agregar un nuevo objeto al EntitySet materia. Considere la posibilidad de usar el método .Add de la propiedad ObjectSet&lt;T&gt; asociada.
        /// </summary>
        public void AddTomateria(materia materia)
        {
            base.AddObject("materia", materia);
        }

        #endregion
    }
    

    #endregion
    
    #region Entidades
    
    /// <summary>
    /// No hay documentación de metadatos disponible.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="dbuniversidadModel1", Name="carrera")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class carrera : EntityObject
    {
        #region Método de generador
    
        /// <summary>
        /// Crear un nuevo objeto carrera.
        /// </summary>
        /// <param name="codigo">Valor inicial de la propiedad codigo.</param>
        /// <param name="nombre">Valor inicial de la propiedad nombre.</param>
        /// <param name="detalle">Valor inicial de la propiedad detalle.</param>
        public static carrera Createcarrera(global::System.Int32 codigo, global::System.String nombre, global::System.String detalle)
        {
            carrera carrera = new carrera();
            carrera.codigo = codigo;
            carrera.nombre = nombre;
            carrera.detalle = detalle;
            return carrera;
        }

        #endregion
        #region Propiedades primitivas
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 codigo
        {
            get
            {
                return _codigo;
            }
            set
            {
                if (_codigo != value)
                {
                    OncodigoChanging(value);
                    ReportPropertyChanging("codigo");
                    _codigo = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("codigo");
                    OncodigoChanged();
                }
            }
        }
        private global::System.Int32 _codigo;
        partial void OncodigoChanging(global::System.Int32 value);
        partial void OncodigoChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String nombre
        {
            get
            {
                return _nombre;
            }
            set
            {
                OnnombreChanging(value);
                ReportPropertyChanging("nombre");
                _nombre = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("nombre");
                OnnombreChanged();
            }
        }
        private global::System.String _nombre;
        partial void OnnombreChanging(global::System.String value);
        partial void OnnombreChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String detalle
        {
            get
            {
                return _detalle;
            }
            set
            {
                OndetalleChanging(value);
                ReportPropertyChanging("detalle");
                _detalle = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("detalle");
                OndetalleChanged();
            }
        }
        private global::System.String _detalle;
        partial void OndetalleChanging(global::System.String value);
        partial void OndetalleChanged();

        #endregion
    
        #region Propiedades de navegación
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("dbuniversidadModel1", "FK__estudiant__codig__0BC6C43E", "estudiante")]
        public EntityCollection<estudiante> estudiante
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<estudiante>("dbuniversidadModel1.FK__estudiant__codig__0BC6C43E", "estudiante");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<estudiante>("dbuniversidadModel1.FK__estudiant__codig__0BC6C43E", "estudiante", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No hay documentación de metadatos disponible.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="dbuniversidadModel1", Name="detalleEvaluacion")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class detalleEvaluacion : EntityObject
    {
        #region Método de generador
    
        /// <summary>
        /// Crear un nuevo objeto detalleEvaluacion.
        /// </summary>
        /// <param name="codigo">Valor inicial de la propiedad codigo.</param>
        /// <param name="numero">Valor inicial de la propiedad numero.</param>
        /// <param name="nota">Valor inicial de la propiedad nota.</param>
        public static detalleEvaluacion CreatedetalleEvaluacion(global::System.Int32 codigo, global::System.Int32 numero, global::System.Int32 nota)
        {
            detalleEvaluacion detalleEvaluacion = new detalleEvaluacion();
            detalleEvaluacion.codigo = codigo;
            detalleEvaluacion.numero = numero;
            detalleEvaluacion.nota = nota;
            return detalleEvaluacion;
        }

        #endregion
        #region Propiedades primitivas
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 codigo
        {
            get
            {
                return _codigo;
            }
            set
            {
                if (_codigo != value)
                {
                    OncodigoChanging(value);
                    ReportPropertyChanging("codigo");
                    _codigo = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("codigo");
                    OncodigoChanged();
                }
            }
        }
        private global::System.Int32 _codigo;
        partial void OncodigoChanging(global::System.Int32 value);
        partial void OncodigoChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 numero
        {
            get
            {
                return _numero;
            }
            set
            {
                if (_numero != value)
                {
                    OnnumeroChanging(value);
                    ReportPropertyChanging("numero");
                    _numero = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("numero");
                    OnnumeroChanged();
                }
            }
        }
        private global::System.Int32 _numero;
        partial void OnnumeroChanging(global::System.Int32 value);
        partial void OnnumeroChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 nota
        {
            get
            {
                return _nota;
            }
            set
            {
                OnnotaChanging(value);
                ReportPropertyChanging("nota");
                _nota = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("nota");
                OnnotaChanged();
            }
        }
        private global::System.Int32 _nota;
        partial void OnnotaChanging(global::System.Int32 value);
        partial void OnnotaChanged();

        #endregion
    
        #region Propiedades de navegación
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("dbuniversidadModel1", "FK__detalleEv__codig__15502E78", "estudiante")]
        public estudiante estudiante
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<estudiante>("dbuniversidadModel1.FK__detalleEv__codig__15502E78", "estudiante").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<estudiante>("dbuniversidadModel1.FK__detalleEv__codig__15502E78", "estudiante").Value = value;
            }
        }
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<estudiante> estudianteReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<estudiante>("dbuniversidadModel1.FK__detalleEv__codig__15502E78", "estudiante");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<estudiante>("dbuniversidadModel1.FK__detalleEv__codig__15502E78", "estudiante", value);
                }
            }
        }
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("dbuniversidadModel1", "FK__detalleEv__numer__164452B1", "evaluacion")]
        public evaluacion evaluacion
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<evaluacion>("dbuniversidadModel1.FK__detalleEv__numer__164452B1", "evaluacion").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<evaluacion>("dbuniversidadModel1.FK__detalleEv__numer__164452B1", "evaluacion").Value = value;
            }
        }
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<evaluacion> evaluacionReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<evaluacion>("dbuniversidadModel1.FK__detalleEv__numer__164452B1", "evaluacion");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<evaluacion>("dbuniversidadModel1.FK__detalleEv__numer__164452B1", "evaluacion", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No hay documentación de metadatos disponible.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="dbuniversidadModel1", Name="estudiante")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class estudiante : EntityObject
    {
        #region Método de generador
    
        /// <summary>
        /// Crear un nuevo objeto estudiante.
        /// </summary>
        /// <param name="codigo">Valor inicial de la propiedad codigo.</param>
        /// <param name="nombre">Valor inicial de la propiedad nombre.</param>
        /// <param name="paterno">Valor inicial de la propiedad paterno.</param>
        /// <param name="materno">Valor inicial de la propiedad materno.</param>
        /// <param name="genero">Valor inicial de la propiedad genero.</param>
        /// <param name="correo">Valor inicial de la propiedad correo.</param>
        /// <param name="telefono">Valor inicial de la propiedad telefono.</param>
        /// <param name="codigoc">Valor inicial de la propiedad codigoc.</param>
        public static estudiante Createestudiante(global::System.Int32 codigo, global::System.String nombre, global::System.String paterno, global::System.String materno, global::System.String genero, global::System.String correo, global::System.Int32 telefono, global::System.Int32 codigoc)
        {
            estudiante estudiante = new estudiante();
            estudiante.codigo = codigo;
            estudiante.nombre = nombre;
            estudiante.paterno = paterno;
            estudiante.materno = materno;
            estudiante.genero = genero;
            estudiante.correo = correo;
            estudiante.telefono = telefono;
            estudiante.codigoc = codigoc;
            return estudiante;
        }

        #endregion
        #region Propiedades primitivas
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 codigo
        {
            get
            {
                return _codigo;
            }
            set
            {
                if (_codigo != value)
                {
                    OncodigoChanging(value);
                    ReportPropertyChanging("codigo");
                    _codigo = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("codigo");
                    OncodigoChanged();
                }
            }
        }
        private global::System.Int32 _codigo;
        partial void OncodigoChanging(global::System.Int32 value);
        partial void OncodigoChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String nombre
        {
            get
            {
                return _nombre;
            }
            set
            {
                OnnombreChanging(value);
                ReportPropertyChanging("nombre");
                _nombre = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("nombre");
                OnnombreChanged();
            }
        }
        private global::System.String _nombre;
        partial void OnnombreChanging(global::System.String value);
        partial void OnnombreChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String paterno
        {
            get
            {
                return _paterno;
            }
            set
            {
                OnpaternoChanging(value);
                ReportPropertyChanging("paterno");
                _paterno = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("paterno");
                OnpaternoChanged();
            }
        }
        private global::System.String _paterno;
        partial void OnpaternoChanging(global::System.String value);
        partial void OnpaternoChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String materno
        {
            get
            {
                return _materno;
            }
            set
            {
                OnmaternoChanging(value);
                ReportPropertyChanging("materno");
                _materno = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("materno");
                OnmaternoChanged();
            }
        }
        private global::System.String _materno;
        partial void OnmaternoChanging(global::System.String value);
        partial void OnmaternoChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String genero
        {
            get
            {
                return _genero;
            }
            set
            {
                OngeneroChanging(value);
                ReportPropertyChanging("genero");
                _genero = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("genero");
                OngeneroChanged();
            }
        }
        private global::System.String _genero;
        partial void OngeneroChanging(global::System.String value);
        partial void OngeneroChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String correo
        {
            get
            {
                return _correo;
            }
            set
            {
                OncorreoChanging(value);
                ReportPropertyChanging("correo");
                _correo = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("correo");
                OncorreoChanged();
            }
        }
        private global::System.String _correo;
        partial void OncorreoChanging(global::System.String value);
        partial void OncorreoChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 telefono
        {
            get
            {
                return _telefono;
            }
            set
            {
                OntelefonoChanging(value);
                ReportPropertyChanging("telefono");
                _telefono = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("telefono");
                OntelefonoChanged();
            }
        }
        private global::System.Int32 _telefono;
        partial void OntelefonoChanging(global::System.Int32 value);
        partial void OntelefonoChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 codigoc
        {
            get
            {
                return _codigoc;
            }
            set
            {
                OncodigocChanging(value);
                ReportPropertyChanging("codigoc");
                _codigoc = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("codigoc");
                OncodigocChanged();
            }
        }
        private global::System.Int32 _codigoc;
        partial void OncodigocChanging(global::System.Int32 value);
        partial void OncodigocChanged();

        #endregion
    
        #region Propiedades de navegación
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("dbuniversidadModel1", "FK__estudiant__codig__0BC6C43E", "carrera")]
        public carrera carrera
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<carrera>("dbuniversidadModel1.FK__estudiant__codig__0BC6C43E", "carrera").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<carrera>("dbuniversidadModel1.FK__estudiant__codig__0BC6C43E", "carrera").Value = value;
            }
        }
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<carrera> carreraReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<carrera>("dbuniversidadModel1.FK__estudiant__codig__0BC6C43E", "carrera");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<carrera>("dbuniversidadModel1.FK__estudiant__codig__0BC6C43E", "carrera", value);
                }
            }
        }
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("dbuniversidadModel1", "FK__detalleEv__codig__15502E78", "detalleEvaluacion")]
        public EntityCollection<detalleEvaluacion> detalleEvaluacion
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<detalleEvaluacion>("dbuniversidadModel1.FK__detalleEv__codig__15502E78", "detalleEvaluacion");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<detalleEvaluacion>("dbuniversidadModel1.FK__detalleEv__codig__15502E78", "detalleEvaluacion", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No hay documentación de metadatos disponible.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="dbuniversidadModel1", Name="evaluacion")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class evaluacion : EntityObject
    {
        #region Método de generador
    
        /// <summary>
        /// Crear un nuevo objeto evaluacion.
        /// </summary>
        /// <param name="numero">Valor inicial de la propiedad numero.</param>
        /// <param name="nombre">Valor inicial de la propiedad nombre.</param>
        /// <param name="detalle">Valor inicial de la propiedad detalle.</param>
        /// <param name="puntaje">Valor inicial de la propiedad puntaje.</param>
        /// <param name="sigla">Valor inicial de la propiedad sigla.</param>
        public static evaluacion Createevaluacion(global::System.Int32 numero, global::System.String nombre, global::System.String detalle, global::System.Int32 puntaje, global::System.String sigla)
        {
            evaluacion evaluacion = new evaluacion();
            evaluacion.numero = numero;
            evaluacion.nombre = nombre;
            evaluacion.detalle = detalle;
            evaluacion.puntaje = puntaje;
            evaluacion.sigla = sigla;
            return evaluacion;
        }

        #endregion
        #region Propiedades primitivas
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 numero
        {
            get
            {
                return _numero;
            }
            set
            {
                if (_numero != value)
                {
                    OnnumeroChanging(value);
                    ReportPropertyChanging("numero");
                    _numero = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("numero");
                    OnnumeroChanged();
                }
            }
        }
        private global::System.Int32 _numero;
        partial void OnnumeroChanging(global::System.Int32 value);
        partial void OnnumeroChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String nombre
        {
            get
            {
                return _nombre;
            }
            set
            {
                OnnombreChanging(value);
                ReportPropertyChanging("nombre");
                _nombre = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("nombre");
                OnnombreChanged();
            }
        }
        private global::System.String _nombre;
        partial void OnnombreChanging(global::System.String value);
        partial void OnnombreChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String detalle
        {
            get
            {
                return _detalle;
            }
            set
            {
                OndetalleChanging(value);
                ReportPropertyChanging("detalle");
                _detalle = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("detalle");
                OndetalleChanged();
            }
        }
        private global::System.String _detalle;
        partial void OndetalleChanging(global::System.String value);
        partial void OndetalleChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 puntaje
        {
            get
            {
                return _puntaje;
            }
            set
            {
                OnpuntajeChanging(value);
                ReportPropertyChanging("puntaje");
                _puntaje = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("puntaje");
                OnpuntajeChanged();
            }
        }
        private global::System.Int32 _puntaje;
        partial void OnpuntajeChanging(global::System.Int32 value);
        partial void OnpuntajeChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String sigla
        {
            get
            {
                return _sigla;
            }
            set
            {
                OnsiglaChanging(value);
                ReportPropertyChanging("sigla");
                _sigla = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("sigla");
                OnsiglaChanged();
            }
        }
        private global::System.String _sigla;
        partial void OnsiglaChanging(global::System.String value);
        partial void OnsiglaChanged();

        #endregion
    
        #region Propiedades de navegación
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("dbuniversidadModel1", "FK__detalleEv__numer__164452B1", "detalleEvaluacion")]
        public EntityCollection<detalleEvaluacion> detalleEvaluacion
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<detalleEvaluacion>("dbuniversidadModel1.FK__detalleEv__numer__164452B1", "detalleEvaluacion");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<detalleEvaluacion>("dbuniversidadModel1.FK__detalleEv__numer__164452B1", "detalleEvaluacion", value);
                }
            }
        }
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("dbuniversidadModel1", "FK__evaluacio__sigla__108B795B", "materia")]
        public materia materia
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<materia>("dbuniversidadModel1.FK__evaluacio__sigla__108B795B", "materia").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<materia>("dbuniversidadModel1.FK__evaluacio__sigla__108B795B", "materia").Value = value;
            }
        }
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<materia> materiaReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<materia>("dbuniversidadModel1.FK__evaluacio__sigla__108B795B", "materia");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<materia>("dbuniversidadModel1.FK__evaluacio__sigla__108B795B", "materia", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No hay documentación de metadatos disponible.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="dbuniversidadModel1", Name="materia")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class materia : EntityObject
    {
        #region Método de generador
    
        /// <summary>
        /// Crear un nuevo objeto materia.
        /// </summary>
        /// <param name="sigla">Valor inicial de la propiedad sigla.</param>
        /// <param name="nombre">Valor inicial de la propiedad nombre.</param>
        /// <param name="detalle">Valor inicial de la propiedad detalle.</param>
        public static materia Createmateria(global::System.String sigla, global::System.String nombre, global::System.String detalle)
        {
            materia materia = new materia();
            materia.sigla = sigla;
            materia.nombre = nombre;
            materia.detalle = detalle;
            return materia;
        }

        #endregion
        #region Propiedades primitivas
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String sigla
        {
            get
            {
                return _sigla;
            }
            set
            {
                if (_sigla != value)
                {
                    OnsiglaChanging(value);
                    ReportPropertyChanging("sigla");
                    _sigla = StructuralObject.SetValidValue(value, false);
                    ReportPropertyChanged("sigla");
                    OnsiglaChanged();
                }
            }
        }
        private global::System.String _sigla;
        partial void OnsiglaChanging(global::System.String value);
        partial void OnsiglaChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String nombre
        {
            get
            {
                return _nombre;
            }
            set
            {
                OnnombreChanging(value);
                ReportPropertyChanging("nombre");
                _nombre = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("nombre");
                OnnombreChanged();
            }
        }
        private global::System.String _nombre;
        partial void OnnombreChanging(global::System.String value);
        partial void OnnombreChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String detalle
        {
            get
            {
                return _detalle;
            }
            set
            {
                OndetalleChanging(value);
                ReportPropertyChanging("detalle");
                _detalle = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("detalle");
                OndetalleChanged();
            }
        }
        private global::System.String _detalle;
        partial void OndetalleChanging(global::System.String value);
        partial void OndetalleChanged();

        #endregion
    
        #region Propiedades de navegación
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("dbuniversidadModel1", "FK__evaluacio__sigla__108B795B", "evaluacion")]
        public EntityCollection<evaluacion> evaluacion
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<evaluacion>("dbuniversidadModel1.FK__evaluacio__sigla__108B795B", "evaluacion");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<evaluacion>("dbuniversidadModel1.FK__evaluacio__sigla__108B795B", "evaluacion", value);
                }
            }
        }

        #endregion
    }

    #endregion
    
}
